# This workflow will install Python dependencies and run tests with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Build and test package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow}}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  build:
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ['3.8', '3.9', '3.10']
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: mamba-org/provision-with-micromamba@main
      with:
        environment-file: false
        environment-name: CI
        extra-specs: python=${{ matrix.python-version }}
        channels: conda-forge
        cache-env: true
        cache-env-key: mamba-${{ runner.os }}-${{ matrix.python-version}}-${{ hashFiles('ci/*') }}
    - name: Install dependencies
      run: micromamba install --quiet --yes --file ci/test_requirements.txt --file ci/requirements.txt
    - name: Install package
      run: python -m pip install --no-deps .
    - name: Test package
      run: pytest
